version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    # For development, you can mount the source code as a volume
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DB_URL=jdbc:postgresql://db:5432/inventory
      - DB_USER=postgres
      - DB_PASS=postgres
      - JWT_SECRET=your-secret-key

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: